// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvchLNdm5ahHKu9GQdNa5yoItU_JFasvI',
    appId: '1:538110339684:web:1c345fcbca2fe96c5f0d71',
    messagingSenderId: '538110339684',
    projectId: 'crud-01-diario',
    authDomain: 'crud-01-diario.firebaseapp.com',
    databaseURL: 'https://crud-01-diario-default-rtdb.firebaseio.com',
    storageBucket: 'crud-01-diario.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDylzVeuGEKWkfF1PLhsZU8SmpsKvo3Nag',
    appId: '1:538110339684:android:938ffdaf94d8d2395f0d71',
    messagingSenderId: '538110339684',
    projectId: 'crud-01-diario',
    databaseURL: 'https://crud-01-diario-default-rtdb.firebaseio.com',
    storageBucket: 'crud-01-diario.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIGuuioOKY8O4IeuiUWLAI6IcdeNJsYeQ',
    appId: '1:538110339684:ios:247c51178d95d01d5f0d71',
    messagingSenderId: '538110339684',
    projectId: 'crud-01-diario',
    databaseURL: 'https://crud-01-diario-default-rtdb.firebaseio.com',
    storageBucket: 'crud-01-diario.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppMercado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIGuuioOKY8O4IeuiUWLAI6IcdeNJsYeQ',
    appId: '1:538110339684:ios:247c51178d95d01d5f0d71',
    messagingSenderId: '538110339684',
    projectId: 'crud-01-diario',
    databaseURL: 'https://crud-01-diario-default-rtdb.firebaseio.com',
    storageBucket: 'crud-01-diario.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppMercado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvchLNdm5ahHKu9GQdNa5yoItU_JFasvI',
    appId: '1:538110339684:web:f352f5cadbe52cb55f0d71',
    messagingSenderId: '538110339684',
    projectId: 'crud-01-diario',
    authDomain: 'crud-01-diario.firebaseapp.com',
    databaseURL: 'https://crud-01-diario-default-rtdb.firebaseio.com',
    storageBucket: 'crud-01-diario.firebasestorage.app',
  );

}